* 适用比较适用在数值比较集中的情况

* 缺陷：如果max和min不稳定，很容易使得归一化结果不稳定，使得后续使用效果也不稳定。实际使用中可以用经验常量来替代max和min。

* 应用场景：在不涉及距离度量、协方差计算、数据不符合正太分布的时候，可以使用第一种方法或其他归一化方法（不包括Z-score方法）。比如图像处理中，将RGB图像转换为灰度图像后将其值限定在[0  255]的范围

In [1]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [2]:
X = np.array([
    [1, -1, 2, 3],
    [2, 0, 0, 3],
    [0, 1, -1, 3]
], dtype=np.float64)

In [3]:
scaler = MinMaxScaler(feature_range=(1,5))
scaler.fit(X)

MinMaxScaler(copy=True, feature_range=(1, 5))

In [6]:
print (scaler.data_max_)
print (scaler.data_min_)
print (scaler.data_range_)

[2. 1. 2. 3.]
[ 0. -1. -1.  3.]
[2. 2. 3. 0.]


In [7]:
print (scaler.transform(X))

[[3.         1.         5.         1.        ]
 [5.         3.         2.33333333 1.        ]
 [1.         5.         1.         1.        ]]


In [17]:
X_std = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
print(X_std)
#X_scaled = X_std * (max - min) + min
X_scaled = X_std * (5 - 1) + 1
print(X_scaled)
X_scaled[np.isnan(X_scaled)]=1.
print(X_scaled)

[[0.5        0.         1.                nan]
 [1.         0.5        0.33333333        nan]
 [0.         1.         0.                nan]]
[[3.         1.         5.                nan]
 [5.         3.         2.33333333        nan]
 [1.         5.         1.                nan]]
[[3.         1.         5.         1.        ]
 [5.         3.         2.33333333 1.        ]
 [1.         5.         1.         1.        ]]


D:\TOOL\zwPython\py36\python-3.6.2.amd64\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
